from fpdf import FPDF


def createPDF(title, text, output_filename, destination="F"):
    # print("Creating PDF...")
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", style="B", size=16)
    title_width = pdf.get_string_width(title)
    x_title = (pdf.w - title_width) / 2
    pdf.cell(200, 10, txt=title, ln=True, align="C")
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 10, txt=text, align="J")
    pdf.output(output_filename, dest=destination)


# One of the story generated by the model.
"""
Title: "Chasing Dreams"

FADE IN:

EXT. PARK - DAY

A little boy, JASON, stands on a grass field, holding a frisbee in his hand. He looks up at the sky with a determined look on his face.

JASON (V.O.) I want to be the best player in the world.

He throws the frisbee high into the air and catches it with one hand, then runs towards the goal post, slamming the disc through it. He jumps up, looking at his progress with pride.

JASON (V.O.) But first, I have to prove myself.

He continues to play, facing off against other kids in the park, each time getting better and more confident.

CUT TO:

INT. COACH'S OFFICE - DAY

Coach Johnson watches Jason's game from behind a desk, taking notes on a clipboard. He gets up and approaches him.

COACH JOHNSON You have potential, kid. But you need to work harder.

Jason nods, determined to take the coach's advice to heart.

CUT TO:

EXT. PARK - DAY

Jason practices every day, perfecting his throws and learning new techniques from his coach. He becomes known as the best player in the park, drawing crowds of kids to watch him play.

CUT TO:

INT. COACH'S OFFICE - DAY

Coach Johnson watches Jason practice, a proud smile on his face.

COACH JOHNSON You're a natural, kid. But don't get complacent. Keep pushing yourself.

Jason nods, taking the coach's words to heart. He continues to work hard and improve his skills.

CUT TO:

EXT. PARK - DAY

Months have passed, and Jason has become a skilled frisbee player, able to perform tricks and stunts that leave other players in awe. He competes in tournaments and wins first place every time.

CUT TO:

INT. COACH'S OFFICE - DAY

Coach Johnson watches Jason play on TV, cheering him on.

COACH JOHNSON
"""
